[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"
  NODE_VERSION = "20" 